In [19]:
import src.logic.processing as p
import src.logic.severa.client

from importlib import reload

reload(p)
reload(src.logic.severa.client)

import arrow
from src.util.daterange import DateRange

last_sunday = arrow.utcnow().shift(weeks=-1).ceil("weeks")
span = DateRange(arrow.get("2023-06-01"), arrow.get("2023-10-30"))

# 2023-04-01end=2023-11-30

print(span)

#df = await p.load_and_merge(span, True)
#df2 = await p.load_merge_pivot(span, window=28, contractor_user_ids=["5cd93092-3385-3e89-003a-9fe6d03a424d"])

2023-06-01 .. 2023-10-30

In [20]:
async with src.logic.severa.client.Client() as client:
    d = await client.fetch_sales(filtered_keywords=["Tie_Puitesopimus", "Tie_Pois_raportoinnista"])

2023-11-22 08:55:39.494 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET salescases in 0.09s.
2023-11-22 08:55:39.497 | DEBUG    | src.logic.severa.client:fetch_single_sale:509 - Match! [ModelWithName(guid='815256ee-3b54-68f4-a233-9604980b05d7', name='Tie_Tietomallikoordinointi'), ModelWithName(guid='50ac0c3b-78e6-e66f-fb48-4329a7a08ee7', name='Tie_Puitesopimus')]
2023-11-22 08:55:39.500 | DEBUG    | src.logic.severa.client:fetch_single_sale:509 - Match! [ModelWithName(guid='815256ee-3b54-68f4-a233-9604980b05d7', name='Tie_Tietomallikoordinointi'), ModelWithName(guid='50ac0c3b-78e6-e66f-fb48-4329a7a08ee7', name='Tie_Puitesopimus')]
2023-11-22 08:55:39.604 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/edad67bd-9c5b-bbeb-5567-0559c1378e3d/phaseswithhierarchy in 0.11s.
2023-11-22 08:55:39.615 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/f62568a5-36ce-5dc3-490d-a3a24031dba1/phaseswithhierarchy in 0.11s.
2023-11-22 08:55:39.627 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/61529c7f-7919-1050-9f5c-2d07668a864a/phaseswithhierarchy in 0.12s.
2023-11-22 08:55:39.637 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/7748c380-e045-eeab-cf2b-c0ce35525602/phaseswithhierarchy in 0.12s.
2023-11-22 08:55:39.650 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/d7b71871-6910-2314-0784-dd28a25da033/phaseswithhierarchy in 0.14s.
2023-11-22 08:55:39.664 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/e98335f5-2e3c-bd4a-611f-7bc87c09dc8f/phaseswithhierarchy in 0.17s.
2023-11-22 08:55:39.675 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/b7ee21ab-90b9-cb28-0698-af24fc18931c/phaseswithhierarchy in 0.17s.
2023-11-22 08:55:39.690 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/8094282a-b7f6-a0ff-16a6-a5367d4ea694/phaseswithhierarchy in 0.17s.
2023-11-22 08:55:39.824 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/fc2bc783-95c5-bbc8-bc3d-e8ffe90556c6/phaseswithhierarchy in 0.31s.
2023-11-22 08:55:40.492 | SUCCESS  | src.logic.severa.base_client:get_with_retries:196 - HTTP/2 GET projects/2328e64a-4dcb-9c6f-fdcc-2becd164e8e0/phaseswithhierarchy in 0.08s.

In [15]:
d

Empty DataFrame
Columns: []
Index: []

In [24]:
df2.reset_index().iloc[[-8, -1]]

id,date,absences,billing,hour_cost,maximum,salesvalue,workhours,workhours_productive,workhours_unproductive,total_hours,cost,margin,margin%,billing_rate,uncounted_hours
29,2023-08-14 00:00:00+00:00,506.375,12966.33,13679.0,1207.5,8580.0,653.00,314.25,338.75,1159.375,56840.640625,-43874.310625,-3.383711,0.48124,48.125
35,2023-08-20 00:00:00+00:00,313.625,15232.33,13937.0,1237.5,16965.0,828.75,452.00,376.75,1142.375,55703.953125,-40471.623125,-2.656956,0.54540,95.125

In [31]:
import pandas as pd

def windowfy(data_raw, window=30):
    prod_work = data_raw[(data_raw.id == "workhours") & data_raw.productive].copy()
    prod_work["id"] = "workhours_productive"
    unprod_work = data_raw[(data_raw.id == "workhours") & ~data_raw.productive].copy()
    unprod_work["id"] = "workhours_unproductive"

    data_concat = pd.concat([data_raw, prod_work, unprod_work], ignore_index=True)

    

    data_pivoted = data_concat.pivot_table(
        values=["value"],
        index=["date", "first_name"],
        columns=["id"],
        aggfunc="sum",
        fill_value=0,
    )
    data_pivoted.columns = data_pivoted.columns.droplevel(0)

    data_pivoted["total_hours"] = data_pivoted["absences"] + data_pivoted["workhours"]
    data_pivoted["cost"] = data_pivoted["total_hours"] * data_pivoted["hour_cost"]
    data_pivoted["margin"] = data_pivoted["billing"] - data_pivoted["cost"]

    # return data_pivoted

    data_windowed = data_pivoted.groupby(["date"]).sum().rolling(window=window).sum()

    data_windowed["margin%"] = data_windowed["margin"] / data_windowed["billing"]
    data_windowed["billing_rate"] = (
        data_windowed["workhours_productive"] / data_windowed["workhours"]
    )
    data_windowed["uncounted_hours"] = (
        data_windowed["maximum"] - data_windowed["total_hours"]
    )
    return data_windowed

In [32]:
windowfy(df)

id,absences,billing,hour_cost,maximum,salesvalue,workhours,workhours_productive,workhours_unproductive,total_hours,cost,margin,margin%,billing_rate,uncounted_hours
date,,,,,,,,,,,,,,
2023-07-15 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-16 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-17 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-18 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-19 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-20 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-21 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-22 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-23 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-24 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-25 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-26 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-27 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-28 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-29 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-30 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-31 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-01 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-02 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-03 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-04 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-05 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-06 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-07 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-08 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-09 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-10 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-11 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-12 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-13 00:00:00+00:00,562.0625,12966.33,14610.0,1230.0,8580.0,588.00,263.75,324.25,1150.0625,56467.218750,-43500.888750,-3.354911,0.448554,79.9375
2023-08-14 00:00:00+00:00,562.0625,12966.33,14653.0,1299.0,8580.0,653.00,314.25,338.75,1215.0625,59579.218750,-46612.888750,-3.594918,0.481240,83.9375
2023-08-15 00:00:00+00:00,562.0625,12966.33,14696.0,1368.0,8580.0,706.00,362.50,343.50,1268.0625,62112.218750,-49145.888750,-3.790270,0.513456,99.9375
2023-08-16 00:00:00+00:00,506.3750,15066.33,14739.0,1375.5,8580.0,757.50,403.50,354.00,1263.8750,61836.390625,-46770.060625,-3.104277,0.532673,111.6250
2023-08-17 00:00:00+00:00,458.1875,17522.33,14782.0,1383.0,8580.0,801.50,437.00,364.50,1259.6875,61546.812500,-44024.482500,-2.512479,0.545228,123.3125
2023-08-18 00:00:00+00:00,417.5000,17522.33,14825.0,1390.5,16965.0,829.75,450.50,379.25,1247.2500,60886.109375,-43363.779375,-2.474772,0.542935,143.2500
2023-08-19 00:00:00+00:00,369.3125,17522.33,14868.0,1329.0,16965.0,828.75,452.00,376.75,1198.0625,58442.531250,-40920.201250,-2.335317,0.545400,130.9375
2023-08-20 00:00:00+00:00,313.6250,15232.33,14911.0,1267.5,16965.0,828.75,452.00,376.75,1142.3750,55703.953125,-40471.623125,-2.656956,0.545400,125.1250
2023-08-21 00:00:00+00:00,313.6250,20147.21,14954.0,1336.5,16965.0,851.75,471.50,380.25,1165.3750,56771.203125,-36623.993125,-1.817820,0.553566,171.1250
2023-08-22 00:00:00+00:00,313.6250,21707.21,14997.0,1405.5,16965.0,867.25,484.50,382.75,1180.8750,57534.953125,-35827.743125,-1.650500,0.558662,224.6250
2023-08-23 00:00:00+00:00,263.5625,21707.21,15040.0,1413.0,16965.0,864.25,482.00,382.25,1127.8125,54909.625000,-33202.415000,-1.529557,0.557709,285.1875
2023-08-24 00:00:00+00:00,213.5000,21707.21,15083.0,1420.5,16965.0,857.75,475.50,382.25,1071.2500,52121.296875,-30414.086875,-1.401105,0.554357,349.2500